const CATALOG = [
  {
    id: "001",
    name: "Assassin's Creed Valhalla – Ragnarok Edition",
    platform: "Xbox Series X",
    img: "/img/valhalla.jpg",
    price: 3999,
  },
  {
    id: "002",
    name: "Star Wars Jedi: Fallen Order",
    platform: "Xbox Series X",
    img: "/img/fallenoreder.jpg",
    price: 1699,
  },
  {
    id: "003",
    name: "DOOM Eternal",
    platform: "Xbox Series X",
    img: "/img/doom.jpg",
    price: 3199,
  },
  {
    id: "004",
    name: "Watch Dogs: Legion – Resistance Edition",
    platform: "Xbox Series X",
    img: "/img/wdlegion.jpg",
    price: 1999,
  },
  {
    id: "005",
    name: "Star Wars: Squadrons",
    platform: "Xbox Series X",
    img: "/img/swsquadrons.jpg",
    price: 2199,
  },
  {
    id: "006",
    name: "Battlefield 2042",
    platform: "Xbox Series X",
    img: "/img/bf2042.jpg",
    price: 2299,
  },
  {
    id: "007",
    name: "Back 4 Blood – Special Edition",
    platform: "Xbox Series X",
    img: "/img/b4b.jpg",
    price: 2499,
  },
  {
    id: "008",
    name: "Grand Theft Auto V – Premium Edition",
    platform: "Xbox Series X",
    img: "/img/gtav.jpg",
    price: 2699,
  },
  {
    id: "009",
    name: "Call of Duty: Vanguard",
    platform: "Xbox Series X",
    img: "/img/cod.jpg",
    price: 2999,
  },
  {
    id: "010",
    name: "Far Cry 6 – Yara Edition",
    platform: "Xbox Series X",
    img: "/img/fc6.jpg",
    price: 3999,
  },
];
